### ISSUE TITLE
Data management 

### ISSUE THREAD

**Issue by haondt** [CMPUT301F18T01/MDBook#27]
We don't exactly have a well-defined approach to saving data in cache, in memory and in the cloud. Someone needs to sort that out.

One idea is to split the elasticsearch controller into a memory controller who's duty is to keep the three memory methods in sync. From there it can interact with an elasticsearch controller, a memory controller and a cache controller. The cache controller I assume would be coupled with the usercontroller and/or the usermanager? Not sure, just a start I supposed.

Whatever we go with, don't forget to update the UML diagram.

**Comment by haondt** [comment]
Just another thought, this should probably be where we handle collisions. For example;
- If the user tries to create an account while disconnected, there's no way to ensure the userID is unique. I suggest we don't allow profile creation without an internet connection.
- If the user makes changes, such as adding a photo or a record or something while not connected, the changes are stashed locally. Once internet connection is re-established,
  - Pure additions are just added 
  - Conflicting edits are changed to the most recent one
  - Deletions are pushed through with highest priority. I.e. if one copy of the data indicates a record is deleted, and another, let's say newer one, suggests the record has been edited but still exists, the deletion has higher priority and both databases are updated to have the record deleted.

**Comment by haondt** [comment]
So, I started getting pretty heavy into this in the [Elasticsearch-contoller](https://github.com/CMPUT301F18T01/MDBook/tree/Elasticsearch-controller) branch. I've added a ContactUser object for storing partial user profiles, namely the contact information so we can avoid loading a users problems and records when we only need basic profile info.

The elasticsearch controller is starting to become pretty complex. I'm thinking it's more of a general data manager at this point. It would be good to rename it to a cache manager and then implement a new elasticsearch controller and storage controller. Then we could have a data manager that syncs the three, it would be pretty straightforward since all of the data is currently kept in HashMaps with JSONObjects as the values and user/problem/record IDs as the keys.

**Comment by haondt** [comment]
Split the elasticsearch controller into two pieces, one for managing the saving and loading of users and user attributes and another class, SearchController, for searching, which includes:
- finding a record or problem by keyword
- finding a record or problem by geolocation
- retrieving the patientID associated with a given record or problem.

**Comment by haondt** [comment]
Removed all the methods from the elasticsearch controller and moved them into user manager. Elasticsearch controller will have the express purpose of keeping datamanager in sync with cloud storage.

**Comment by jay064** [comment]
so according to that, Elasticsearch controller will not have any of the methods that make searching using keywords possible

**Comment by haondt** [comment]
> so according to that, Elasticsearch controller will not have any of the methods that make searching using keywords possible

Yeah that would be the job of SearchController

**Comment by haondt** [comment]
Finished user manager (going to add tests) and datamanager and pushed to master #36. @tcchan97 is working on the local and elastic search controllers in a seperate branch

**Comment by haondt** [comment]
updated uml to match model from #36 via #42.

**Comment by tcchan97** [comment]
Most of local data controller is done, just need to implement deleting and I worked a but on storing data in elastic search

**Comment by haondt** [comment]
completed via #53, though the tests still need some fixes #52
