### ISSUE TITLE
Elasticsearch controller tests don't clear test data out of elasticsearch

### ISSUE THREAD

**Issue by haondt** [CMPUT301F18T01/MDBook#52]
Filling idlists with nonsensical test data that needs to be cleared out after the test runs

**Comment by Vanessa0122** [comment]
You guys can probably do this 



    @After
    public void tearDown() throws Exception {
        LoginActivity = null;
        RegisterActivity = null;
        ListProblemActivity = null;
        EditProblemDetailsActivity = null;
        AddProblemActivity = null;
        ViewAccountDetailActivity = null;
        EditAccountDetailsActivity = null;
        ViewRecordActivity = null;
        AddRecordActivity = null;
        PatientSearchActivity = null;
        PatientSlideActivity = null;
    }

**Comment by haondt** [comment]
fixed (test-wise) in [es-tests](https://github.com/CMPUT301F18T01/MDBook/tree/es-tests) via a4d79f4. deleteUser method isn't fully implemented yet.
