### ISSUE TITLE
Async Task

### ISSUE THREAD

**Issue by haondt** [CMPUT301F18T01/MDBook#58]
Had a bunch of issues come up when trying to integrate data storage with login/register activities. One was the LocalStorageController having improperly configured as a singleton. Another was it creating an infinite loop with the datamanager. both of those have been  fixed in the branch [Usermanager-fix](https://github.com/CMPUT301F18T01/MDBook/tree/Usermanager-fix).

A new issue arises, the elasticsearch controller needs to be updated to perform networking tasks in a thread other than main, using AsyncTask.

**Comment by tcchan97** [comment]
What do you mean it was improperly configured as a singleton

**Comment by haondt** [comment]
1) It had an infinitely recursive call to new datamanager (fixed via 1d2fddd)
2) It was trying to hold a Context object in a static reference (which is a memory leak). Context was replaced with SharedPrefs (via 3f060b4)

**Comment by haondt** [comment]
completed via #62 and #67
