### ISSUE TITLE
Registering Users issue

### ISSUE THREAD

**Issue by tcchan97** [CMPUT301F18T01/MDBook#64]
App closes when username is not long enough, username has to be greater than 8 characters. Change it show it displays a toast message saying the username is not long enough.

Change Usermanager.C -> line 88

**Comment by tcchan97** [comment]
Another Issue I noticed is that when pressing the back button it closes the entire activity, I can easily fix this but I will do it after data passing is working

**Comment by haondt** [comment]
Which activity is not supposed to close when you hit the back button?

**Comment by haondt** [comment]
fixed via 9c9d440
