### ISSUE TITLE
ListView on ViewRecordActivity is not updating

### ISSUE THREAD

**Issue by Vanessa0122** [CMPUT301F18T01/MDBook#66]
ListView on ViewRecordActivity is not updating after the user adds a new record.

**Comment by Jydobee** [comment]
How are you passing the new record added into the custom adapter?

**Comment by Vanessa0122** [comment]
there is getIntent().getExtra().getSerializable(), it is sucessfully passed (we printed in toast message) but we don't know how to put that in to the list view.

**Comment by Vanessa0122** [comment]
See ViewRecordActivity and AddRecordActivity

**Comment by tcchan97** [comment]
No not yet im still working on this.

**Comment by haondt** [comment]
> Should I close this issue? There is an addRecord issue on the board too

@Vanessa0122 which is the addRecord issue you are referring to? #79 ?

**Comment by Vanessa0122** [comment]
Sorry, they are different issues. This one is not done but #79 is resolved.

**Comment by tcchan97** [comment]
This is resolved in my new data-passing-geolocation branch [https://github.com/CMPUT301F18T01/MDBook/tree/0b0d7b9250240d1267757f657604f348d1b44b44](url)
