### ISSUE TITLE
Saving reminders and notification activity

### ISSUE THREAD

**Issue by rkkapadia** [CMPUT301F18T01/MDBook#76]
US 02.09.01

As a patient, I want some method of helping me take consistent photos so that when I show the doctor any progression such as the growth of a mole is evident.

I need to figure out how to save in local storage and set reminders... I have decided to daily reminders at the time selected by the user.

**Comment by Vanessa0122** [comment]
This was done by Raj and Vanessa on November 29th 5-9:30 PM.
