### ISSUE TITLE
Adding comments to patient records for caregiver

### ISSUE THREAD

**Issue by rkkapadia** [CMPUT301F18T01/MDBook#77]
US 02.07.01
As a care provider, I want to add new comment records to a problem for my patients.

**Comment by rkkapadia** [comment]
working in branch pass-data-caregiver, done, just need to review

**Comment by Vanessa0122** [comment]
NOTE: ORDER OF THE COMMENTS NEED TO BE SORTED

**Comment by haondt** [comment]
Hey so I'm just kinda loosely following the work done on this branch, and just had a couple questions.
Firstly, should we implement a class specifically for comment records? And what exactly is a comment record? Just a record that contains a comment exclusively? 
Secondly, what is the purpose of the comment class (ff8de99)? Why not just have a string?

**Comment by rkkapadia** [comment]
Ok, I was trying to sort it by time or date added, and it became all messed up.

And yeah I created a new record with a title "Caregiver says:" and to that new object, I just used the setComment method you implemented in your record class... it does the job.

**Comment by rkkapadia** [comment]
Comments are working fine.

**Comment by haondt** [comment]
merged via #85
