### ISSUE TITLE
use case numbers 

### ISSUE THREAD

**Issue by haondt** [CMPUT301F18T01/MDBook#8]
numbers are too arbitrary and needs to list associated use cases

**Comment by jay064** [comment]
Completed most use case numbers, just having trouble mapping certain user stories onto already established use cases.  Use cases available in the wiki under requirement specification.

**Comment by haondt** [comment]
> Completed most use case numbers, just having trouble mapping certain user stories onto already established use cases. Use cases available in the wiki under requirement specification.

Can you mention exactly which user stories you are having trouble mapping? like list the US-numbers.

**Comment by rkkapadia** [comment]
Completed, sorted by US numbers.
