### ISSUE TITLE
UML Update for Activities

### ISSUE THREAD

**Issue by Jydobee** [CMPUT301F18T01/MDBook#81]

**Comment by Jydobee** [comment]
The following Activities were just recently created and need to be incorporated into the UML:
(1) AddCommentActivity (2) AddPatientActivity (3) Add ProblemActivity (4)AddRecordActivity (5)AddReminderActivity (6) MapActivity (7) NotificationActivity (8) ListRecordCGActivity 

Please comment any other new activity created that I haven't included in the list

**Comment by rkkapadia** [comment]
Just to add, I don't know if you already added or not RecordCGAdapter was also added

**Comment by Jydobee** [comment]
AddPatientActivity has been incorporated into the UML Diagram

**Comment by Jydobee** [comment]
ListRecordCGActivity has been incorporated into the UML Diagram

**Comment by Jydobee** [comment]
Completed
