### ISSUE TITLE
Fixing date issues

### ISSUE THREAD

**Issue by rkkapadia** [CMPUT301F18T01/MDBook#88]
User should be able to create a problem by inputting the date, records should be created with a timestamp.

Working in branch patient-date.

**Comment by rkkapadia** [comment]
Currently implementing datePicker in ListProblemActivity

**Comment by rkkapadia** [comment]
Records now have timestamp. commit abd18b25ff5c279ec5e1d1b6917a7c1ddf45b3fb

**Comment by Vanessa0122** [comment]
Awesome, we can close this issue now.
