### ISSUE TITLE
Problem class needs to accommodate for dates

### ISSUE THREAD

**Issue by rkkapadia** [CMPUT301F18T01/MDBook#89]
According to US 01.01.01

"As a patient, I want to record my problems, each denoted with a title, date started, and a brief description", 

A date needs to be added to storage for problems.

**Comment by rkkapadia** [comment]
I have edited the Problem class adding setters and getters and the constructor, in branch patient-date.

**Comment by Vanessa0122** [comment]
[[NOTE: Patient's problems needs to be sorted by date in recycler view.]]

**Comment by rkkapadia** [comment]
I don't think patient problems should be ordered by date. Instead, the most recent problem added can have a different date then the current date because users are able to select a date instead of it being automatic.

**Comment by Vanessa0122** [comment]
Ok, that means we are done with this issue?

**Comment by rkkapadia** [comment]
On our end yes, but someone needs to add dates for problems to the server and storage. I don't we can do that, has to be Noah or Thomas, I have talked with Noah this morning about it.

**Comment by Vanessa0122** [comment]
Um, that would be another issue. I will close this and open another one
