### ISSUE TITLE
use case exceptions

### ISSUE THREAD

**Issue by haondt** [CMPUT301F18T01/MDBook#9]
need to add flow and exceptions to use case

**Comment by Jydobee** [comment]
I am currently adding the Basic flow and exceptions to the Use cases

**Comment by haondt** [comment]
edits are being made first in a google doc - https://docs.google.com/document/d/12YqsemjdsKNx2egJSAnvIz7aL6AAg3jIpNIjcqYeMJI

**Comment by rkkapadia** [comment]
Added exceptions and basic flow

**Comment by Jydobee** [comment]
Exceptions and Basic flow have been included
