### ISSUE TITLE
Store Date in ElasticSearch

### ISSUE THREAD

**Issue by Vanessa0122** [CMPUT301F18T01/MDBook#91]
Patient will pick a start date when they are adding a new problem. It needs to be stored in elasticsearch

**Comment by Vanessa0122** [comment]
It needs to be added to elastic

**Comment by haondt** [comment]
front end I believe is completed via #93, back end implementation still needs to be done

**Comment by haondt** [comment]
completed in [es-tests](https://github.com/CMPUT301F18T01/MDBook/tree/es-tests) via 9f15bebdc25dbf89ba3e1ad66e004ab001220690
