### ISSUE TITLE
Unable to add 2 problems. 

### ISSUE THREAD

**Issue by Vanessa0122** [CMPUT301F18T01/MDBook#94]
1. Click add button on list problem activity 
2. Add Problem 1 and enter description 
3. Problem saved, shows on list 
4. Click add button on list problem activity 
5. Enter Problem 2 and description 
6. Click save and app crashed. 
BUG IN LISTPROBLEMACTIVITY.

**Comment by rkkapadia** [comment]
I think this is got to do with elastic search retrieving previous problems, so I think this is a backend problem

**Comment by haondt** [comment]
fixed via #99
